/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_praseodym_activelearner_AFL */

#ifndef _Included_net_praseodym_activelearner_AFL
#define _Included_net_praseodym_activelearner_AFL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_praseodym_activelearner_AFL_hello
  (JNIEnv *, jobject);

/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    pre
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_praseodym_activelearner_AFL_pre
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    post
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_praseodym_activelearner_AFL_post
  (JNIEnv *, jobject);

/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    run
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_praseodym_activelearner_AFL_run
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    getQueuedDiscovered
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_praseodym_activelearner_AFL_getQueuedDiscovered
  (JNIEnv *, jobject);

/*
 * Class:     net_praseodym_activelearner_AFL
 * Method:    getTraceBitmap
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_praseodym_activelearner_AFL_getTraceBitmap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
